FROM node:18.13.0 as build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container


# Copy the rest of the application code to the container
COPY . .

COPY db.json .

RUN npm install --force

RUN npm i -g json-server --force

RUN npm install -g @angular/cli@15.1.6

RUN ng build

FROM nginx:stable

COPY --from=build /app/dist/challenge /usr/share/nginx/html

EXPOSE 80 
