FROM node:18.13.0 as build

# Set the working directory to /app
WORKDIR /app

# Copy the package.json and package-lock.json files to the container
COPY package*.json ./

RUN npm install --force

# Copy the rest of the application code to the container
COPY . .

RUN npm install -g @angular/cli@15.1.6
RUN ng build

# Expose the port on which the application will run
EXPOSE 80

# Define the command to run the application
CMD ["npm", "run", "serve:ssr"]
